//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFMTYP_team02.AdService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdService.IAdCRUD")]
    public interface IAdCRUD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/insertAd", ReplyAction="http://tempuri.org/IAdCRUD/insertAdResponse")]
        int insertAd(string Title, string Platform, System.DateTime CreatedDate, string Description, string Location, double Price, int Negotiable, int ShowNumber, string Pic1Path, string Pic2Path, string Pic3Path, int PremiumAd, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/insertAd", ReplyAction="http://tempuri.org/IAdCRUD/insertAdResponse")]
        System.Threading.Tasks.Task<int> insertAdAsync(string Title, string Platform, System.DateTime CreatedDate, string Description, string Location, double Price, int Negotiable, int ShowNumber, string Pic1Path, string Pic2Path, string Pic3Path, int PremiumAd, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/deleteAd", ReplyAction="http://tempuri.org/IAdCRUD/deleteAdResponse")]
        int deleteAd(int AdID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/deleteAd", ReplyAction="http://tempuri.org/IAdCRUD/deleteAdResponse")]
        System.Threading.Tasks.Task<int> deleteAdAsync(int AdID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/updateAd", ReplyAction="http://tempuri.org/IAdCRUD/updateAdResponse")]
        int updateAd(int AdID, string Title, string Platform, string Description, string Location, double Price, int Negotiable, int ShowNumber, string Pic1Path, string Pic2Path, string Pic3Path, int PremiumAd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/updateAd", ReplyAction="http://tempuri.org/IAdCRUD/updateAdResponse")]
        System.Threading.Tasks.Task<int> updateAdAsync(int AdID, string Title, string Platform, string Description, string Location, double Price, int Negotiable, int ShowNumber, string Pic1Path, string Pic2Path, string Pic3Path, int PremiumAd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getAdDetails", ReplyAction="http://tempuri.org/IAdCRUD/getAdDetailsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[] getAdDetails(string AdID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getAdDetails", ReplyAction="http://tempuri.org/IAdCRUD/getAdDetailsResponse")]
        System.Threading.Tasks.Task<object[]> getAdDetailsAsync(string AdID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getEditAdDetails", ReplyAction="http://tempuri.org/IAdCRUD/getEditAdDetailsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[] getEditAdDetails(string AdID, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getEditAdDetails", ReplyAction="http://tempuri.org/IAdCRUD/getEditAdDetailsResponse")]
        System.Threading.Tasks.Task<object[]> getEditAdDetailsAsync(string AdID, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/searchAds", ReplyAction="http://tempuri.org/IAdCRUD/searchAdsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[][] searchAds(string searchTerm, string extraSQLParams, string extraSQLOrderBys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/searchAds", ReplyAction="http://tempuri.org/IAdCRUD/searchAdsResponse")]
        System.Threading.Tasks.Task<object[][]> searchAdsAsync(string searchTerm, string extraSQLParams, string extraSQLOrderBys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getPlatforms", ReplyAction="http://tempuri.org/IAdCRUD/getPlatformsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[] getPlatforms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getPlatforms", ReplyAction="http://tempuri.org/IAdCRUD/getPlatformsResponse")]
        System.Threading.Tasks.Task<object[]> getPlatformsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getUserAds", ReplyAction="http://tempuri.org/IAdCRUD/getUserAdsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[][] getUserAds(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getUserAds", ReplyAction="http://tempuri.org/IAdCRUD/getUserAdsResponse")]
        System.Threading.Tasks.Task<object[][]> getUserAdsAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getRecentlyAdded", ReplyAction="http://tempuri.org/IAdCRUD/getRecentlyAddedResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[][] getRecentlyAdded();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getRecentlyAdded", ReplyAction="http://tempuri.org/IAdCRUD/getRecentlyAddedResponse")]
        System.Threading.Tasks.Task<object[][]> getRecentlyAddedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getNumUserAds", ReplyAction="http://tempuri.org/IAdCRUD/getNumUserAdsResponse")]
        int getNumUserAds(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getNumUserAds", ReplyAction="http://tempuri.org/IAdCRUD/getNumUserAdsResponse")]
        System.Threading.Tasks.Task<int> getNumUserAdsAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getFlaggedAdsManagement", ReplyAction="http://tempuri.org/IAdCRUD/getFlaggedAdsManagementResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[][] getFlaggedAdsManagement();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getFlaggedAdsManagement", ReplyAction="http://tempuri.org/IAdCRUD/getFlaggedAdsManagementResponse")]
        System.Threading.Tasks.Task<object[][]> getFlaggedAdsManagementAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getAllAdsManagement", ReplyAction="http://tempuri.org/IAdCRUD/getAllAdsManagementResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[][] getAllAdsManagement();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getAllAdsManagement", ReplyAction="http://tempuri.org/IAdCRUD/getAllAdsManagementResponse")]
        System.Threading.Tasks.Task<object[][]> getAllAdsManagementAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/searchAdsManagement", ReplyAction="http://tempuri.org/IAdCRUD/searchAdsManagementResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[][] searchAdsManagement(string searchTerm, string extraSQLParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/searchAdsManagement", ReplyAction="http://tempuri.org/IAdCRUD/searchAdsManagementResponse")]
        System.Threading.Tasks.Task<object[][]> searchAdsManagementAsync(string searchTerm, string extraSQLParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getUserEmail", ReplyAction="http://tempuri.org/IAdCRUD/getUserEmailResponse")]
        string[] getUserEmail(int aID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getUserEmail", ReplyAction="http://tempuri.org/IAdCRUD/getUserEmailResponse")]
        System.Threading.Tasks.Task<string[]> getUserEmailAsync(int aID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/unflagAd", ReplyAction="http://tempuri.org/IAdCRUD/unflagAdResponse")]
        int unflagAd(int adID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/unflagAd", ReplyAction="http://tempuri.org/IAdCRUD/unflagAdResponse")]
        System.Threading.Tasks.Task<int> unflagAdAsync(int adID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/flagAd", ReplyAction="http://tempuri.org/IAdCRUD/flagAdResponse")]
        int flagAd(int adID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/flagAd", ReplyAction="http://tempuri.org/IAdCRUD/flagAdResponse")]
        System.Threading.Tasks.Task<int> flagAdAsync(int adID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/reportAd", ReplyAction="http://tempuri.org/IAdCRUD/reportAdResponse")]
        int reportAd(int adID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/reportAd", ReplyAction="http://tempuri.org/IAdCRUD/reportAdResponse")]
        System.Threading.Tasks.Task<int> reportAdAsync(int adID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/unreportAd", ReplyAction="http://tempuri.org/IAdCRUD/unreportAdResponse")]
        int unreportAd(int adID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/unreportAd", ReplyAction="http://tempuri.org/IAdCRUD/unreportAdResponse")]
        System.Threading.Tasks.Task<int> unreportAdAsync(int adID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getReportedAdsManagement", ReplyAction="http://tempuri.org/IAdCRUD/getReportedAdsManagementResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[][] getReportedAdsManagement();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getReportedAdsManagement", ReplyAction="http://tempuri.org/IAdCRUD/getReportedAdsManagementResponse")]
        System.Threading.Tasks.Task<object[][]> getReportedAdsManagementAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getUsersAdsManagement", ReplyAction="http://tempuri.org/IAdCRUD/getUsersAdsManagementResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[][] getUsersAdsManagement(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getUsersAdsManagement", ReplyAction="http://tempuri.org/IAdCRUD/getUsersAdsManagementResponse")]
        System.Threading.Tasks.Task<object[][]> getUsersAdsManagementAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/numNewAdsYearManagement", ReplyAction="http://tempuri.org/IAdCRUD/numNewAdsYearManagementResponse")]
        int numNewAdsYearManagement(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/numNewAdsYearManagement", ReplyAction="http://tempuri.org/IAdCRUD/numNewAdsYearManagementResponse")]
        System.Threading.Tasks.Task<int> numNewAdsYearManagementAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/numNewAdsMonthManagement", ReplyAction="http://tempuri.org/IAdCRUD/numNewAdsMonthManagementResponse")]
        int numNewAdsMonthManagement(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/numNewAdsMonthManagement", ReplyAction="http://tempuri.org/IAdCRUD/numNewAdsMonthManagementResponse")]
        System.Threading.Tasks.Task<int> numNewAdsMonthManagementAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/numNewAdsWeekManagement", ReplyAction="http://tempuri.org/IAdCRUD/numNewAdsWeekManagementResponse")]
        int numNewAdsWeekManagement(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/numNewAdsWeekManagement", ReplyAction="http://tempuri.org/IAdCRUD/numNewAdsWeekManagementResponse")]
        System.Threading.Tasks.Task<int> numNewAdsWeekManagementAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/numNewAdsDayManagement", ReplyAction="http://tempuri.org/IAdCRUD/numNewAdsDayManagementResponse")]
        int numNewAdsDayManagement(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/numNewAdsDayManagement", ReplyAction="http://tempuri.org/IAdCRUD/numNewAdsDayManagementResponse")]
        System.Threading.Tasks.Task<int> numNewAdsDayManagementAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/numReportedAdsManagement", ReplyAction="http://tempuri.org/IAdCRUD/numReportedAdsManagementResponse")]
        int numReportedAdsManagement();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/numReportedAdsManagement", ReplyAction="http://tempuri.org/IAdCRUD/numReportedAdsManagementResponse")]
        System.Threading.Tasks.Task<int> numReportedAdsManagementAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/numFlaggedAdsManagement", ReplyAction="http://tempuri.org/IAdCRUD/numFlaggedAdsManagementResponse")]
        int numFlaggedAdsManagement();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/numFlaggedAdsManagement", ReplyAction="http://tempuri.org/IAdCRUD/numFlaggedAdsManagementResponse")]
        System.Threading.Tasks.Task<int> numFlaggedAdsManagementAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/numPremAdsManagement", ReplyAction="http://tempuri.org/IAdCRUD/numPremAdsManagementResponse")]
        int numPremAdsManagement();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/numPremAdsManagement", ReplyAction="http://tempuri.org/IAdCRUD/numPremAdsManagementResponse")]
        System.Threading.Tasks.Task<int> numPremAdsManagementAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/incViewCount", ReplyAction="http://tempuri.org/IAdCRUD/incViewCountResponse")]
        int incViewCount(int aID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/incViewCount", ReplyAction="http://tempuri.org/IAdCRUD/incViewCountResponse")]
        System.Threading.Tasks.Task<int> incViewCountAsync(int aID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getViewCount", ReplyAction="http://tempuri.org/IAdCRUD/getViewCountResponse")]
        int getViewCount(int aID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdCRUD/getViewCount", ReplyAction="http://tempuri.org/IAdCRUD/getViewCountResponse")]
        System.Threading.Tasks.Task<int> getViewCountAsync(int aID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdCRUDChannel : IFMTYP_team02.AdService.IAdCRUD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdCRUDClient : System.ServiceModel.ClientBase<IFMTYP_team02.AdService.IAdCRUD>, IFMTYP_team02.AdService.IAdCRUD {
        
        public AdCRUDClient() {
        }
        
        public AdCRUDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdCRUDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdCRUDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdCRUDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int insertAd(string Title, string Platform, System.DateTime CreatedDate, string Description, string Location, double Price, int Negotiable, int ShowNumber, string Pic1Path, string Pic2Path, string Pic3Path, int PremiumAd, int UserID) {
            return base.Channel.insertAd(Title, Platform, CreatedDate, Description, Location, Price, Negotiable, ShowNumber, Pic1Path, Pic2Path, Pic3Path, PremiumAd, UserID);
        }
        
        public System.Threading.Tasks.Task<int> insertAdAsync(string Title, string Platform, System.DateTime CreatedDate, string Description, string Location, double Price, int Negotiable, int ShowNumber, string Pic1Path, string Pic2Path, string Pic3Path, int PremiumAd, int UserID) {
            return base.Channel.insertAdAsync(Title, Platform, CreatedDate, Description, Location, Price, Negotiable, ShowNumber, Pic1Path, Pic2Path, Pic3Path, PremiumAd, UserID);
        }
        
        public int deleteAd(int AdID) {
            return base.Channel.deleteAd(AdID);
        }
        
        public System.Threading.Tasks.Task<int> deleteAdAsync(int AdID) {
            return base.Channel.deleteAdAsync(AdID);
        }
        
        public int updateAd(int AdID, string Title, string Platform, string Description, string Location, double Price, int Negotiable, int ShowNumber, string Pic1Path, string Pic2Path, string Pic3Path, int PremiumAd) {
            return base.Channel.updateAd(AdID, Title, Platform, Description, Location, Price, Negotiable, ShowNumber, Pic1Path, Pic2Path, Pic3Path, PremiumAd);
        }
        
        public System.Threading.Tasks.Task<int> updateAdAsync(int AdID, string Title, string Platform, string Description, string Location, double Price, int Negotiable, int ShowNumber, string Pic1Path, string Pic2Path, string Pic3Path, int PremiumAd) {
            return base.Channel.updateAdAsync(AdID, Title, Platform, Description, Location, Price, Negotiable, ShowNumber, Pic1Path, Pic2Path, Pic3Path, PremiumAd);
        }
        
        public object[] getAdDetails(string AdID) {
            return base.Channel.getAdDetails(AdID);
        }
        
        public System.Threading.Tasks.Task<object[]> getAdDetailsAsync(string AdID) {
            return base.Channel.getAdDetailsAsync(AdID);
        }
        
        public object[] getEditAdDetails(string AdID, int userID) {
            return base.Channel.getEditAdDetails(AdID, userID);
        }
        
        public System.Threading.Tasks.Task<object[]> getEditAdDetailsAsync(string AdID, int userID) {
            return base.Channel.getEditAdDetailsAsync(AdID, userID);
        }
        
        public object[][] searchAds(string searchTerm, string extraSQLParams, string extraSQLOrderBys) {
            return base.Channel.searchAds(searchTerm, extraSQLParams, extraSQLOrderBys);
        }
        
        public System.Threading.Tasks.Task<object[][]> searchAdsAsync(string searchTerm, string extraSQLParams, string extraSQLOrderBys) {
            return base.Channel.searchAdsAsync(searchTerm, extraSQLParams, extraSQLOrderBys);
        }
        
        public object[] getPlatforms() {
            return base.Channel.getPlatforms();
        }
        
        public System.Threading.Tasks.Task<object[]> getPlatformsAsync() {
            return base.Channel.getPlatformsAsync();
        }
        
        public object[][] getUserAds(int userID) {
            return base.Channel.getUserAds(userID);
        }
        
        public System.Threading.Tasks.Task<object[][]> getUserAdsAsync(int userID) {
            return base.Channel.getUserAdsAsync(userID);
        }
        
        public object[][] getRecentlyAdded() {
            return base.Channel.getRecentlyAdded();
        }
        
        public System.Threading.Tasks.Task<object[][]> getRecentlyAddedAsync() {
            return base.Channel.getRecentlyAddedAsync();
        }
        
        public int getNumUserAds(int userID) {
            return base.Channel.getNumUserAds(userID);
        }
        
        public System.Threading.Tasks.Task<int> getNumUserAdsAsync(int userID) {
            return base.Channel.getNumUserAdsAsync(userID);
        }
        
        public object[][] getFlaggedAdsManagement() {
            return base.Channel.getFlaggedAdsManagement();
        }
        
        public System.Threading.Tasks.Task<object[][]> getFlaggedAdsManagementAsync() {
            return base.Channel.getFlaggedAdsManagementAsync();
        }
        
        public object[][] getAllAdsManagement() {
            return base.Channel.getAllAdsManagement();
        }
        
        public System.Threading.Tasks.Task<object[][]> getAllAdsManagementAsync() {
            return base.Channel.getAllAdsManagementAsync();
        }
        
        public object[][] searchAdsManagement(string searchTerm, string extraSQLParams) {
            return base.Channel.searchAdsManagement(searchTerm, extraSQLParams);
        }
        
        public System.Threading.Tasks.Task<object[][]> searchAdsManagementAsync(string searchTerm, string extraSQLParams) {
            return base.Channel.searchAdsManagementAsync(searchTerm, extraSQLParams);
        }
        
        public string[] getUserEmail(int aID) {
            return base.Channel.getUserEmail(aID);
        }
        
        public System.Threading.Tasks.Task<string[]> getUserEmailAsync(int aID) {
            return base.Channel.getUserEmailAsync(aID);
        }
        
        public int unflagAd(int adID) {
            return base.Channel.unflagAd(adID);
        }
        
        public System.Threading.Tasks.Task<int> unflagAdAsync(int adID) {
            return base.Channel.unflagAdAsync(adID);
        }
        
        public int flagAd(int adID) {
            return base.Channel.flagAd(adID);
        }
        
        public System.Threading.Tasks.Task<int> flagAdAsync(int adID) {
            return base.Channel.flagAdAsync(adID);
        }
        
        public int reportAd(int adID) {
            return base.Channel.reportAd(adID);
        }
        
        public System.Threading.Tasks.Task<int> reportAdAsync(int adID) {
            return base.Channel.reportAdAsync(adID);
        }
        
        public int unreportAd(int adID) {
            return base.Channel.unreportAd(adID);
        }
        
        public System.Threading.Tasks.Task<int> unreportAdAsync(int adID) {
            return base.Channel.unreportAdAsync(adID);
        }
        
        public object[][] getReportedAdsManagement() {
            return base.Channel.getReportedAdsManagement();
        }
        
        public System.Threading.Tasks.Task<object[][]> getReportedAdsManagementAsync() {
            return base.Channel.getReportedAdsManagementAsync();
        }
        
        public object[][] getUsersAdsManagement(int ID) {
            return base.Channel.getUsersAdsManagement(ID);
        }
        
        public System.Threading.Tasks.Task<object[][]> getUsersAdsManagementAsync(int ID) {
            return base.Channel.getUsersAdsManagementAsync(ID);
        }
        
        public int numNewAdsYearManagement(System.DateTime date) {
            return base.Channel.numNewAdsYearManagement(date);
        }
        
        public System.Threading.Tasks.Task<int> numNewAdsYearManagementAsync(System.DateTime date) {
            return base.Channel.numNewAdsYearManagementAsync(date);
        }
        
        public int numNewAdsMonthManagement(System.DateTime date) {
            return base.Channel.numNewAdsMonthManagement(date);
        }
        
        public System.Threading.Tasks.Task<int> numNewAdsMonthManagementAsync(System.DateTime date) {
            return base.Channel.numNewAdsMonthManagementAsync(date);
        }
        
        public int numNewAdsWeekManagement(System.DateTime date) {
            return base.Channel.numNewAdsWeekManagement(date);
        }
        
        public System.Threading.Tasks.Task<int> numNewAdsWeekManagementAsync(System.DateTime date) {
            return base.Channel.numNewAdsWeekManagementAsync(date);
        }
        
        public int numNewAdsDayManagement(System.DateTime date) {
            return base.Channel.numNewAdsDayManagement(date);
        }
        
        public System.Threading.Tasks.Task<int> numNewAdsDayManagementAsync(System.DateTime date) {
            return base.Channel.numNewAdsDayManagementAsync(date);
        }
        
        public int numReportedAdsManagement() {
            return base.Channel.numReportedAdsManagement();
        }
        
        public System.Threading.Tasks.Task<int> numReportedAdsManagementAsync() {
            return base.Channel.numReportedAdsManagementAsync();
        }
        
        public int numFlaggedAdsManagement() {
            return base.Channel.numFlaggedAdsManagement();
        }
        
        public System.Threading.Tasks.Task<int> numFlaggedAdsManagementAsync() {
            return base.Channel.numFlaggedAdsManagementAsync();
        }
        
        public int numPremAdsManagement() {
            return base.Channel.numPremAdsManagement();
        }
        
        public System.Threading.Tasks.Task<int> numPremAdsManagementAsync() {
            return base.Channel.numPremAdsManagementAsync();
        }
        
        public int incViewCount(int aID) {
            return base.Channel.incViewCount(aID);
        }
        
        public System.Threading.Tasks.Task<int> incViewCountAsync(int aID) {
            return base.Channel.incViewCountAsync(aID);
        }
        
        public int getViewCount(int aID) {
            return base.Channel.getViewCount(aID);
        }
        
        public System.Threading.Tasks.Task<int> getViewCountAsync(int aID) {
            return base.Channel.getViewCountAsync(aID);
        }
    }
}
